steps:
- name: 'gcr.io/config-management-release/nomos:v1.14.2'
  args: ['vet', '--no-api-server-check', '--source-format','unstructured','--path','dns-records']
- name: 'gcr.io/kpt-dev/kpt:v1.0.0-beta.29'
  args: ['fn', 'render', '.']
