apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: dnsrecordset-sample-a
  namespace: dns-project
spec:
  name: "www.example.com."
  type: "A"
  ttl: 300
  rrdatas:
  - "8.8.8.8"
