apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: example-dns-zone
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  dnsName: "example.com."
  visibility: private
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: dnsrecordset-sample-a
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  name: "www.example.com."
  type: "A"
  ttl: 300
  managedZoneRef:
    name: example-dns-zone
  rrdatas:
  - "8.8.8.8"
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: dnsrecordset-sample-b
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  name: "test.example.com."
  type: "A"
  ttl: 300
  managedZoneRef:
    name: example-dns-zone
  rrdatas:
  - "8.8.8.8"
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: broken-dns-record
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  name: "test2.example.com."
  type: "A"
  ttl: 300
  managedZoneRef:
    name: example-dns-zone
  rrdatas:
  - "8.8.8.8"